version: '3'

volumes:
  data:
    driver: local
services:
  mysql8:
    image: mysql:8.0.21
    command: --default-authentication-plugin=mysql_native_password
    #restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: test
    ports:
      - 3308:3306
    volumes:
      - ./data/mysql8:/var/lib/mysql
      - ./dev/docker_mariadb_init:/docker-entrypoint-initdb.d


      
      #mysql -uroot -p
      #show databases;
      #show tables;
      #....