version: '3'

volumes:
  data:
    driver: local

services:
  postgres:
    # image: 172.20.1.22/proxy-cache/library/postgres:latest
    image: debezium/postgres:13
    restart: always
    container_name: postgreSQL
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: 123456aA@
      POSTGRES_DB: mypostgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data:rw
      - ./dev/init.sql:/docker-entrypoint-initdb.d/create_tables.sql  


  postgres2:
    # image: 172.20.1.22/proxy-cache/library/postgres:latest
    image: debezium/postgres:13
    restart: always
    container_name: postgreSQL2
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: 123456aA@
      POSTGRES_DB: mypostgres2
    ports:
      - "5433:5432"
    volumes:
      - ./data/postgres2:/var/lib/postgresql/data:rw
      - ./dev/init.sql:/docker-entrypoint-initdb.d/create_tables.sql   